# Generated by Django 5.1.7 on 2025-04-23 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальный идентификатор типа уведомления', max_length=100, unique=True, verbose_name='Название')),
                ('display_name', models.CharField(help_text='Название типа уведомления для отображения', max_length=100, verbose_name='Отображаемое название')),
                ('description', models.TextField(blank=True, help_text='Описание типа уведомления', null=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, help_text='Класс иконки для отображения', max_length=50, null=True, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, help_text='Используется ли данный тип уведомлений', verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип уведомления',
                'verbose_name_plural': 'Типы уведомлений',
                'db_table': 'notification_types',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(help_text='Заголовок уведомления', max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(help_text='Текст уведомления', verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, help_text='Было ли уведомление прочитано', verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, help_text='Время, когда уведомление было прочитано', null=True, verbose_name='Время прочтения')),
                ('entity_type', models.CharField(blank=True, help_text='Тип связанной сущности (Item, User, TradeOffer и т.д.)', max_length=100, null=True, verbose_name='Тип сущности')),
                ('entity_id', models.PositiveIntegerField(blank=True, help_text='ID связанной сущности', null=True, verbose_name='ID сущности')),
                ('action_url', models.CharField(blank=True, help_text='URL для перехода по уведомлению', max_length=255, null=True, verbose_name='URL действия')),
                ('image_url', models.CharField(blank=True, help_text='URL изображения для уведомления', max_length=255, null=True, verbose_name='URL изображения')),
                ('recipient', models.ForeignKey(help_text='Пользователь, получающий уведомление', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='notifications.notificationtype', verbose_name='Тип уведомления')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('token', models.CharField(help_text='Push-токен устройства', max_length=255, unique=True, verbose_name='Токен')),
                ('device_type', models.CharField(help_text='Тип устройства (android, ios и т.д.)', max_length=50, verbose_name='Тип устройства')),
                ('device_name', models.CharField(blank=True, help_text='Название устройства пользователя', max_length=100, null=True, verbose_name='Название устройства')),
                ('is_active', models.BooleanField(default=True, help_text='Используется ли токен для отправки уведомлений', verbose_name='Активен')),
                ('last_used', models.DateTimeField(blank=True, help_text='Дата последнего использования токена', null=True, verbose_name='Последнее использование')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Push-токен',
                'verbose_name_plural': 'Push-токены',
                'db_table': 'push_tokens',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_template', models.CharField(help_text='Шаблон для заголовка уведомления с переменными в формате {variable}', max_length=255, verbose_name='Шаблон заголовка')),
                ('body_template', models.TextField(help_text='Шаблон для текста уведомления с переменными в формате {variable}', verbose_name='Шаблон сообщения')),
                ('language_code', models.CharField(default='ru', help_text='Код языка (ISO) для шаблона', max_length=10, verbose_name='Код языка')),
                ('is_default', models.BooleanField(default=False, help_text='Является ли этот шаблон используемым по умолчанию для данного типа', verbose_name='По умолчанию')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='notifications.notificationtype', verbose_name='Тип уведомления')),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
                'db_table': 'notification_templates',
                'unique_together': {('notification_type', 'language_code')},
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, help_text='Отправлять уведомления по email', verbose_name='Email')),
                ('push_enabled', models.BooleanField(default=True, help_text='Отправлять push-уведомления', verbose_name='Push')),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Показывать уведомления в приложении', verbose_name='В приложении')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='notifications.notificationtype', verbose_name='Тип уведомления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка уведомлений пользователя',
                'verbose_name_plural': 'Настройки уведомлений пользователей',
                'db_table': 'user_notification_preferences',
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
