# Generated by Django 5.1.7 on 2025-05-29 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_location_latitude_alter_location_longitude_and_more'),
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeoffer',
            name='location',
            field=models.ForeignKey(blank=True, help_text='Место встречи для обмена', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_offers', to='profiles.location', verbose_name='Адрес встречи'),
        ),
    ]
