# Generated by Django 5.1.7 on 2025-04-23 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(help_text='Название категории', max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(help_text='URL-совместимое имя категории', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, help_text='Подробное описание категории', null=True, verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, help_text='Иконка или изображение категории', null=True, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать ли категорию в списках', verbose_name='Активна')),
                ('level', models.PositiveSmallIntegerField(default=0, help_text='Уровень вложенности категории в иерархии', verbose_name='Уровень')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Порядок отображения категории в списке', verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, help_text='Родительская категория для создания иерархии', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='categories.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
    ]
