# Generated by Django 5.1.7 on 2025-05-26 21:08

import categories.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, help_text='Иконка или изображение категории', null=True, upload_to=categories.models.category_icon_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Поддерживаемые форматы: JPG, JPEG, PNG, WebP')], verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Отображать ли категорию в списках', verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Уровень вложенности категории в иерархии', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text='Название категории', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Порядок отображения категории в списке', verbose_name='Порядок'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'is_active'], name='cat_parent_active_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level', 'order'], name='cat_level_order_idx'),
        ),
    ]
