# Generated by Django 5.1.7 on 2025-04-23 20:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название типа отзыва', max_length=50, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Подробное описание типа отзыва', null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип отзыва',
                'verbose_name_plural': 'Типы отзывов',
                'db_table': 'review_types',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('rating', models.PositiveSmallIntegerField(help_text='Оценка от 1 до 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, help_text='Текст отзыва', null=True, verbose_name='Комментарий')),
                ('is_hidden', models.BooleanField(default=False, help_text='Скрыт ли отзыв (для модерации)', verbose_name='Скрыт')),
                ('author', models.ForeignKey(help_text='Пользователь, оставивший отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('receiver', models.ForeignKey(help_text='Пользователь, получивший отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('trade_offer', models.ForeignKey(help_text='Обмен, к которому относится отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trades.tradeoffer', verbose_name='Предложение обмена')),
                ('review_type', models.ForeignKey(help_text='Тип отзыва (положительный, отрицательный и т.д.)', on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='reviews.reviewtype', verbose_name='Тип отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
                'ordering': ['-created_at'],
                'unique_together': {('author', 'trade_offer')},
            },
        ),
    ]
