# Generated by Django 5.1.7 on 2025-04-24 02:41

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Географическая широта для геолокации', max_digits=15, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, help_text='Географическая долгота для геолокации', max_digits=15, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Изображение профиля пользователя', null=True, upload_to=profiles.models.user_avatar_path, verbose_name='Аватар'),
        ),
    ]
