# Generated by Django 5.1.7 on 2025-04-23 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли чат', verbose_name='Активен')),
                ('last_message_time', models.DateTimeField(blank=True, help_text='Время отправки последнего сообщения в чате', null=True, verbose_name='Время последнего сообщения')),
                ('participants', models.ManyToManyField(help_text='Пользователи, участвующие в чате', related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('trade_offer', models.ForeignKey(blank=True, help_text='Предложение обмена, к которому относится чат', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat', to='trades.tradeoffer', verbose_name='Предложение обмена')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'db_table': 'chats',
                'ordering': ['-last_message_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('content', models.TextField(help_text='Текст сообщения', verbose_name='Содержание')),
                ('is_read', models.BooleanField(default=False, help_text='Прочитано ли сообщение получателем', verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, help_text='Время, когда сообщение было прочитано', null=True, verbose_name='Время прочтения')),
                ('chat', models.ForeignKey(help_text='Чат, в котором отправлено сообщение', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.chat', verbose_name='Чат')),
                ('sender', models.ForeignKey(help_text='Пользователь, отправивший сообщение', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(help_text='Прикрепленный файл', upload_to='message_attachments/', verbose_name='Файл')),
                ('file_name', models.CharField(help_text='Оригинальное имя файла', max_length=255, verbose_name='Имя файла')),
                ('file_size', models.PositiveIntegerField(help_text='Размер файла в байтах', verbose_name='Размер файла')),
                ('file_type', models.CharField(help_text='MIME-тип файла', max_length=100, verbose_name='Тип файла')),
                ('message', models.ForeignKey(help_text='Сообщение, к которому прикреплено вложение', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='messaging.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение к сообщению',
                'verbose_name_plural': 'Вложения к сообщениям',
                'db_table': 'message_attachments',
            },
        ),
        migrations.CreateModel(
            name='ChatParticipantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_count', models.PositiveIntegerField(default=0, help_text='Количество непрочитанных сообщений', verbose_name='Непрочитанных сообщений')),
                ('is_muted', models.BooleanField(default=False, help_text='Отключены ли уведомления для этого чата', verbose_name='Без уведомлений')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_statuses', to='messaging.chat', verbose_name='Чат')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.message', verbose_name='Последнее прочитанное сообщение')),
            ],
            options={
                'verbose_name': 'Статус участника чата',
                'verbose_name_plural': 'Статусы участников чатов',
                'db_table': 'chat_participant_statuses',
                'unique_together': {('chat', 'user')},
            },
        ),
    ]
